
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const StorageProvider = {
  AWS_S3: 'AWS_S3',
  FIREBASE: 'FIREBASE',
  CLOUDINARY: 'CLOUDINARY',
  CLOUDFLARE_R2: 'CLOUDFLARE_R2'
} as const

export type StorageProvider = (typeof StorageProvider)[keyof typeof StorageProvider]
